### ISSUE TITLE
Успеваемость не открывается) 

### ISSUE THREAD

**Issue by SnakeOPM** [TheBandik/db-management-and-automation#1]
Можно переделать в txt

**Comment by TheBandik** [comment]
Не удобно заполнять будет + таблица слишком широкая, поэтому отображение будет таким себе. Чисто оценки можно сделать, но посещаемость, в любом случае, останется xlsx

**Comment by TheBandik** [comment]
> Можно переделать в txt

Не удобно будет заполнять + таблица слишком широкая, поэтому отображаться будет так себе. Может только оценки сделать, но посещаемость, в любом случае, останется в xlsx.
